apiVersion: v1
kind: Pod
metadata:
  name: node.helloworld-kubernetes
  labels:
    app: helloworld
spec:
  containers:
  - name: helloworld-kubernetes
    image: sridhb/helloworld-kubernetes
    ports:
    - name: nodejs-port
      containerPort: 3001
