apiVersion: v1
kind: Pod
metadata:
 name: helloworld.kubernetes.com
 labels:
   app: helloworld
spec:
 containers:
  -name: kubernetes-demo
   image:sridhb/helloworld-kubernetes
  ports:
   -containerPort: 3000