apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  ports:
  - port: 85
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: helloworld
  type: LoadBalancer
