apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld-controller
spec:
  replicas: 2
  selector:
    app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld-kubernetes
        image: sridhb/helloworld-kubernetes
        ports:
        - name: nodejs-port
          containerPort: 3000
